import imgs from '../../img';

const data = {
  allGroup: [
    {
      groupId: 1,
      artistId: 1,
      groupName: 'BTS',
      groupImg: imgs.bts,
      grouplogoImg: imgs.btsPng,
      gradColor: ['#60abe1', '#0b6bb0', '#c7e7ff'],
    },
    {
      groupId: 2,
      artistId: 2,
      groupName: 'TXT',
      groupImg: imgs.txt,
      grouplogoImg: imgs.txtPng,
    },
    {
      groupId: 3,
      artistId: 3,
      groupName: 'New Jeans',
      groupImg: imgs.newJeans,
      grouplogoImg: imgs.newJeansPng,
    },
    {
      groupId: 4,
      artistId: 4,
      groupName: 'SUZY',
      groupImg: imgs.suzy,
      grouplogoImg: imgs.suzyPng,
    },
    {
      groupId: 5,
      artistId: 5,
      groupName: 'LE SSERAFIM',
      groupImg: imgs.lesserafim,
      grouplogoImg: imgs.lesserafimPng,
    },
    {
      groupId: 6,
      artistId: 6,
      groupName: 'IVE',
      groupImg: imgs.ive,
      grouplogoImg: imgs.ivePng,
    },
    {
      groupId: 7,
      artistId: 7,
      groupName: 'STRAY KIDS',
      groupImg: imgs.skids,
      grouplogoImg: imgs.skidsPng,
    },
    {
      groupId: 8,
      artistId: 8,
      groupName: 'NMIXX',
      groupImg: imgs.nmixx,
      grouplogoImg: imgs.nmixxPng,
    },
    {
      groupId: 9,
      artistId: 9,
      groupName: '(G)I-DLE',
      groupImg: imgs.gIdle,
      grouplogoImg: imgs.gIdlePng,
    },
    {
      groupId: 10,
      artistId: 10,
      groupName: 'BLACKPINK',
      groupImg: imgs.blackPink,
      grouplogoImg: imgs.blackPinkPng,
    },
    {
      groupId: 11,
      artistId: 11,
      groupName: 'BIBI',
      groupImg: imgs.bibi,
      grouplogoImg: imgs.bibiPng,
    },
    {
      groupId: 12,
      artistId: 12,
      groupName: 'BOL4',
      groupImg: imgs.bol4,
      grouplogoImg: imgs.bol4Png,
    },
    {
      groupId: 13,
      artistId: 13,
      groupName: 'SEVENTEEN',
      groupImg: imgs.seventeen,
      grouplogoImg: imgs.seventeenPng,
    },
    {
      groupId: 14,
      artistId: 14,
      groupName: 'AKMU',
      groupImg: imgs.akmu,
      grouplogoImg: imgs.akmuPng,
    },
    {
      groupId: 15,
      artistId: 15,
      groupName: 'PENTAGON',
      groupImg: imgs.pentagon,
      grouplogoImg: imgs.pentagonPng,
    },
    {
      groupId: 16,
      artistId: 16,
      groupName: 'IU',
      groupImg: imgs.iu,
      grouplogoImg: imgs.iuPng,
    },
    {
      groupId: 17,
      artistId: 17,
      groupName: 'Apink',
      groupImg: imgs.apink,
      grouplogoImg: imgs.apinkPng,
    },
    {
      groupId: 18,
      artistId: 18,
      groupName: 'SUNMMI',
      groupImg: imgs.summi,
      grouplogoImg: imgs.summiPng,
    },
    {
      groupId: 19,
      artistId: 19,
      groupName: 'ZICO',
      groupImg: imgs.zico,
      grouplogoImg: imgs.zicoPng,
    },
    {
      groupId: 20,
      artistId: 20,
      groupName: 'BamBam',
      groupImg: imgs.bambam,
      grouplogoImg: imgs.bambamPng,
    },
    {
      groupId: 21,
      artistId: 21,
      groupName: 'LEE YOUNG JI',
      groupImg: imgs.youngJi,
      grouplogoImg: imgs.youngJiPng,
    },
    {
      groupId: 22,
      artistId: 22,
      groupName: 'MAMAMOO',
      groupImg: imgs.mmmoo,
      grouplogoImg: imgs.mmmooPng,
    },
    {
      groupId: 23,
      artistId: 23,
      groupName: 'STAYC',
      groupImg: imgs.stayc,
      grouplogoImg: imgs.staycPng,
    },
    {
      groupId: 24,
      artistId: 24,
      groupName: 'HWANG MIN HYUN',
      groupImg: imgs.minhyun,
      grouplogoImg: imgs.minhyunPng,
    },
    {
      groupId: 25,
      artistId: 25,
      groupName: 'PARK BO GUM',
      groupImg: imgs.bogum,
      grouplogoImg: imgs.bogumPng,
    },
  ],
  myGroup: [
    {
      groupId: 1,
      artistId: 1,
      groupName: 'BTS',
      groupImg: imgs.bts,
      grouplogoImg: imgs.btsPng,
    },
    {
      groupId: 2,
      artistId: 2,
      groupName: 'TXT',
      groupImg: imgs.txt,
      grouplogoImg: imgs.txtPng,
    },
  ],
};

export default data;
